[server]
    addr = "127.0.0.1:10230"

[logger]
    path = "../log"

[depends_serve]
    [depends_serve.mysql_config]
        dsn = "mall:Mackie.115@tcp(172.17.172.25:3306)/mall?charset=utf8&parseTime=True&loc=Local&timeout=300ms&readTimeout=200ms&writeTimeout=200ms"